apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elasticsearch
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: elasticsearch
    helm:
      valueFiles:
      - templates/elasticsearch/values.yaml
    repoURL: https://helm.elastic.co
    targetRevision: 7.6.1
