apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    helm:
      parameters:
      - name:  service.type
        value: LoadBalancer
      valueFiles:
      - values.yaml
    repoURL: https://github.com/kubernetes/ingress-nginx.git
    path: charts/ingress-nginx
    targetRevision: HEAD
