# https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    helm:
      values: |
        clusterName: nucleus-rogue-1
        serviceAccount:
          create: false
          name: aws-load-balancer-controller
    chart: eks/aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.3.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
